// src/scripts/import-scraped.ts
// 从 products-data-raw.js 中提取产品数据并导入到博客数据库

const products = [
  {
    slug: "bopp-antifog-film",
    nameEn: "BOPP Anti-Fog Film",
    nameZh: "BOPP防雾薄膜",
    category: "bopp-gloss",
    descriptionEn: "BOPP anti-fog film treated on one or both sides to stop condensation from clouding the pack, keeping fresh produce, meat, seafood and frozen food clearly visible on the shelf.",
    descriptionZh: "BOPP防雾膜经单面或双面防雾处理，可有效防止包装内壁凝露起雾，让新鲜果蔬、肉类、海鲜及冷冻食品在货架上保持清晰可见。",
    thickness: "20-60 microns",
    width: "200-2200mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Anti-fog treatment\nHigh clarity\nHeat sealable\nFood contact grade\nPuncture resistant",
    featuresZh: "防雾处理\n高透明度\n可热封\n食品接触级\n耐穿刺",
    applicationsEn: "Fresh vegetables packaging\nMeat packaging\nSeafood packaging\nFrozen food packaging",
    applicationsZh: "新鲜蔬菜包装\n肉类包装\n海鲜包装\n冷冻食品包装",
    certifications: "FDA\nSGS",
    images: "https://484e5af0.telegraph-image-8xr.pages.dev/file/AgACAgUAAyEGAATkLALaAANgak5Kf7GQdMk83PzooLoRZYVB2GcAAvMSaxttEnBWV0HFBBfcwawBAAMCAAN4AAM8BA.jpg",
    featured: true,
  },
  {
    slug: "bopp-antistatic-film",
    nameEn: "BOPP Anti-Static Film",
    nameZh: "BOPP抗静电膜",
    category: "bopp-printing",
    descriptionEn: "BOPP film with anti-static treatment, suitable for high-speed printing and packaging applications.",
    descriptionZh: "经抗静电处理的BOPP薄膜，适用于高速印刷和包装应用。",
    thickness: "20-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Anti-static treatment\nHigh clarity\nExcellent printability\nGood dimensional stability",
    featuresZh: "抗静电处理\n高透明度\n优异印刷适性\n良好的尺寸稳定性",
    applicationsEn: "Printing\nPackaging\nLabel making",
    applicationsZh: "印刷\n包装\n标签制作",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-antistatic.jpg",
    featured: true,
  },
  {
    slug: "bopp-bag-grade-film",
    nameEn: "BOPP Bag Grade Film",
    nameZh: "BOPP制袋级薄膜",
    category: "bopp-printing",
    descriptionEn: "BOPP film specifically designed for bag making applications with excellent heat sealability.",
    descriptionZh: "专为制袋应用设计的BOPP薄膜，具有优异的热封性能。",
    thickness: "20-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Excellent heat sealability\nHigh clarity\nGood stiffness\nPrintable surface",
    featuresZh: "优异热封性能\n高透明度\n良好挺度\n可印刷表面",
    applicationsEn: "Bag making\nPackaging\nStationery",
    applicationsZh: "制袋\n包装\n文具",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-bag.jpg",
    featured: true,
  },
  {
    slug: "biaxial-oriented-pp-film",
    nameEn: "Biaxially-oriented Polypropylene Film",
    nameZh: "双向拉伸聚丙烯薄膜",
    category: "bopp-printing",
    descriptionEn: "Premium BOPP film with excellent optical properties and mechanical strength for versatile packaging applications.",
    descriptionZh: "优质BOPP薄膜，具有优异的光学性能和机械强度，适用于多种包装应用。",
    thickness: "15-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Excellent optical properties\nHigh tensile strength\nGood barrier properties\nPrintable",
    featuresZh: "优异光学性能\n高拉伸强度\n良好阻隔性\n可印刷",
    applicationsEn: "Food packaging\nPrinting\nLamination",
    applicationsZh: "食品包装\n印刷\n覆膜",
    certifications: "ISO 9001\nFDA\nSGS",
    images: "/images/products/bopp-biaxial.jpg",
    featured: true,
  },
  {
    slug: "bopp-capacitor-film",
    nameEn: "BOPP Capacitor Film",
    nameZh: "BOPP电容器膜",
    category: "bopp-printing",
    descriptionEn: "Specialized BOPP film for capacitor applications with high purity and excellent dielectric properties.",
    descriptionZh: "专用于电容器的BOPP薄膜，具有高纯度和优异的介电性能。",
    thickness: "4-12 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "High purity\nExcellent dielectric properties\nLow dielectric loss\nHigh breakdown voltage",
    featuresZh: "高纯度\n优异介电性能\n低介电损耗\n高击穿电压",
    applicationsEn: "Capacitor manufacturing\nElectronics\nPower systems",
    applicationsZh: "电容器制造\n电子\n电力系统",
    certifications: "ISO 9001\nUL",
    images: "/images/products/bopp-capacitor.jpg",
    featured: true,
  },
  {
    slug: "metallized-bopp-capacitor-film",
    nameEn: "Metallized BOPP Capacitor Film",
    nameZh: "镀铝BOPP电容器膜",
    category: "bopp-printing",
    descriptionEn: "Metallized BOPP film for self-healing capacitor applications with excellent electrical properties.",
    descriptionZh: "用于自愈式电容器的镀铝BOPP薄膜，具有优异的电气性能。",
    thickness: "4-12 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Silver",
    material: "Polypropylene",
    featuresEn: "Self-healing capability\nExcellent electrical properties\nHigh purity\nMetallized surface",
    featuresZh: "自愈能力\n优异电气性能\n高纯度\n镀铝表面",
    applicationsEn: "Capacitor manufacturing\nElectronics\nPower electronics",
    applicationsZh: "电容器制造\n电子\n电力电子",
    certifications: "ISO 9001\nUL",
    images: "/images/products/bopp-metallized-cap.jpg",
    featured: true,
  },
  {
    slug: "bopp-heat-seal-film",
    nameEn: "BOPP Heat Sealable Film",
    nameZh: "BOPP热封膜",
    category: "bopp-printing",
    descriptionEn: "BOPP film with heat sealable coating for packaging applications requiring secure sealing.",
    descriptionZh: "涂有热封涂层的BOPP薄膜，适用于需要牢固密封的包装应用。",
    thickness: "20-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Heat sealable\nHigh clarity\nGood tensile strength\nPrintable surface",
    featuresZh: "可热封\n高透明度\n高拉伸强度\n可印刷表面",
    applicationsEn: "Food packaging\nConfectionery packaging\nSnack packaging",
    applicationsZh: "食品包装\n糖果包装\n零食包装",
    certifications: "ISO 9001\nFDA\nSGS",
    images: "/images/products/bopp-heat-seal.jpg",
    featured: true,
  },
  {
    slug: "bopp-gloss-film",
    nameEn: "BOPP Glossy Film",
    nameZh: "BOPP光膜",
    category: "bopp-printing",
    descriptionEn: "High-gloss BOPP film with exceptional clarity for premium packaging and printing applications.",
    descriptionZh: "高光泽BOPP薄膜，具有卓越的透明度，适用于高端包装和印刷应用。",
    thickness: "15-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "High gloss finish\nExcellent clarity\nGood stiffness\nPrintable",
    featuresZh: "高光泽表面\n优异透明度\n良好挺度\n可印刷",
    applicationsEn: "Printing\nLamination\nGift wrapping",
    applicationsZh: "印刷\n覆膜\n礼品包装",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-gloss.jpg",
    featured: true,
  },
  {
    slug: "bopp-matt-film",
    nameEn: "BOPP Matt Film",
    nameZh: "BOPP哑光膜",
    category: "bopp-printing",
    descriptionEn: "Matte finish BOPP film for premium packaging with sophisticated appearance.",
    descriptionZh: "哑光表面BOPP薄膜，具有高档外观，适用于高端包装。",
    thickness: "15-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Matte finish\nFingerprint resistant\nGood printability\nElegant appearance",
    featuresZh: "哑光表面\n防指纹\n良好印刷适性\n优雅外观",
    applicationsEn: "Premium packaging\nCosmetics packaging\nBook covers",
    applicationsZh: "高端包装\n化妆品包装\n书皮",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-matt.jpg",
    featured: true,
  },
  {
    slug: "bopp-metallized-film",
    nameEn: "BOPP Metallized Film",
    nameZh: "BOPP镀铝膜",
    category: "bopp-printing",
    descriptionEn: "Metallized BOPP film with excellent barrier properties and metallic appearance.",
    descriptionZh: "镀铝BOPP薄膜，具有优异的阻隔性能和金属外观。",
    thickness: "18-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Silver",
    material: "Polypropylene",
    featuresEn: "Excellent barrier properties\nMetallic appearance\nLight blocking\nPrintable",
    featuresZh: "优异阻隔性能\n金属外观\n遮光\n可印刷",
    applicationsEn: "Food packaging\nSnack packaging\nConfectionery",
    applicationsZh: "食品包装\n零食包装\n糖果",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-metallized.jpg",
    featured: true,
  },
  {
    slug: "bopp-pearlized-film",
    nameEn: "BOPP Pearlized Film",
    nameZh: "BOPP珠光膜",
    category: "bopp-printing",
    descriptionEn: "Pearlized BOPP film with beautiful luster and good opacity for decorative packaging.",
    descriptionZh: "珠光BOPP薄膜，具有美丽光泽和良好不透明度，适用于装饰性包装。",
    thickness: "20-50 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "White",
    material: "Polypropylene",
    featuresEn: "Pearl luster\nGood opacity\nHeat sealable\nPrintable",
    featuresZh: "珠光效果\n良好不透明度\n可热封\n可印刷",
    applicationsEn: "Gift wrapping\nFood packaging\nDecorative packaging",
    applicationsZh: "礼品包装\n食品包装\n装饰包装",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-pearlized.jpg",
    featured: true,
  },
  {
    slug: "bopp-shrink-film",
    nameEn: "BOPP Shrink Film",
    nameZh: "BOPP收缩膜",
    category: "bopp-printing",
    descriptionEn: "Oriented BOPP film with shrink properties for secure packaging applications.",
    descriptionZh: "具有收缩性能的拉伸BOPP薄膜，适用于牢固包装应用。",
    thickness: "18-35 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Shrink properties\nHigh clarity\nGood tensile strength\nPrintable",
    featuresZh: "收缩性能\n高透明度\n高拉伸强度\n可印刷",
    applicationsEn: "Product wrapping\nPackaging\nLabeling",
    applicationsZh: "产品包装\n包装\n标签",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-shrink.jpg",
    featured: true,
  },
  {
    slug: "bopp-flower-film",
    nameEn: "BOPP Flower Wrapping Film",
    nameZh: "BOPP花卉包装膜",
    category: "bopp-printing",
    descriptionEn: "Specialized BOPP film for flower wrapping with excellent clarity and flexibility.",
    descriptionZh: "专用于花卉包装的BOPP薄膜，具有优异透明度和柔韧性。",
    thickness: "20-30 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "High clarity\nFlexible\nPrintable\nWater resistant",
    featuresZh: "高透明度\n柔韧\n可印刷\n防水",
    applicationsEn: "Flower wrapping\nBouquet packaging\nGift wrapping",
    applicationsZh: "花卉包装\n花束包装\n礼品包装",
    certifications: "ISO 9001",
    images: "/images/products/bopp-flower.jpg",
    featured: true,
  },
  {
    slug: "bopp-tape-film",
    nameEn: "BOPP Tape Film",
    nameZh: "BOPP胶带基膜",
    category: "bopp-printing",
    descriptionEn: "Base film for adhesive tape production with excellent mechanical properties.",
    descriptionZh: "胶带生产基膜，具有优异的机械性能。",
    thickness: "25-50 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "High tensile strength\nGood dimensional stability\nUniform thickness\nPrintable",
    featuresZh: "高拉伸强度\n良好尺寸稳定性\n厚度均匀\n可印刷",
    applicationsEn: "Adhesive tape production\nPackaging tape\nStationery tape",
    applicationsZh: "胶带生产\n包装胶带\n文具胶带",
    certifications: "ISO 9001",
    images: "/images/products/bopp-tape.jpg",
    featured: true,
  },
  {
    slug: "bopp-thermal-lamination-film",
    nameEn: "BOPP Thermal Lamination Film",
    nameZh: "BOPP覆膜",
    category: "bopp-printing",
    descriptionEn: "BOPP film for thermal lamination with excellent adhesion and appearance.",
    descriptionZh: "用于覆膜的BOPP薄膜，具有优异附着力和外观。",
    thickness: "15-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Excellent adhesion\nHigh clarity\nGood stiffness\nPrintable",
    featuresZh: "优异附着力\n高透明度\n良好挺度\n可印刷",
    applicationsEn: "Book covers\nPackaging\nLabels",
    applicationsZh: "书皮\n包装\n标签",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-thermal.jpg",
    featured: true,
  },
  {
    slug: "bopp-tobacco-film",
    nameEn: "BOPP Tobacco Film",
    nameZh: "BOPP烟包膜",
    category: "bopp-printing",
    descriptionEn: "Specialized BOPP film for cigarette packaging with shrink properties.",
    descriptionZh: "专用于香烟包装的BOPP薄膜，具有收缩性能。",
    thickness: "18-25 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Shrink properties\nHigh clarity\nGood printability\nTear tape compatible",
    featuresZh: "收缩性能\n高透明度\n良好印刷适性\n兼容拉线",
    applicationsEn: "Cigarette packaging\nTobacco packaging",
    applicationsZh: "香烟包装\n烟草包装",
    certifications: "ISO 9001",
    images: "/images/products/bopp-tobacco.jpg",
    featured: true,
  },
  {
    slug: "bopp-white-film",
    nameEn: "BOPP White Film",
    nameZh: "BOPP白膜",
    category: "bopp-printing",
    descriptionEn: "White opaque BOPP film for packaging and printing applications.",
    descriptionZh: "白色不透明BOPP薄膜，适用于包装和印刷应用。",
    thickness: "25-50 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "White",
    material: "Polypropylene",
    featuresEn: "Opaque white\nGood printability\nHeat sealable\nStiff",
    featuresZh: "白色不透明\n良好印刷适性\n可热封\n挺度好",
    applicationsEn: "Packaging\nPrinting\nLabeling",
    applicationsZh: "包装\n印刷\n标签",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-white.jpg",
    featured: true,
  },
  {
    slug: "bopp-perforated-film",
    nameEn: "BOPP Perforated Film",
    nameZh: "BOPP打孔膜",
    category: "bopp-printing",
    descriptionEn: "BOPP film with micro-perforations for breathable packaging applications.",
    descriptionZh: "带有微孔的BOPP薄膜，适用于透气包装应用。",
    thickness: "20-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Micro-perforations\nBreathable\nHigh clarity\nPrintable",
    featuresZh: "微孔\n透气\n高透明度\n可印刷",
    applicationsEn: "Fresh produce packaging\nVegetable packaging\nFruit packaging",
    applicationsZh: "新鲜农产品包装\n蔬菜包装\n水果包装",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-perforated.jpg",
    featured: true,
  },
  {
    slug: "bopp-soft-touch-film",
    nameEn: "BOPP Soft Touch Film",
    nameZh: "BOPP触感膜",
    category: "bopp-printing",
    descriptionEn: "BOPP film with soft-touch coating for premium tactile packaging experience.",
    descriptionZh: "涂有触感涂层的BOPP薄膜，提供高档触觉包装体验。",
    thickness: "25-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Soft-touch coating\nPremium tactile feel\nFingerprint resistant\nPrintable",
    featuresZh: "触感涂层\n高档触感\n防指纹\n可印刷",
    applicationsEn: "Premium packaging\nCosmetics packaging\nLuxury goods",
    applicationsZh: "高端包装\n化妆品包装\n奢侈品",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-soft-touch.jpg",
    featured: true,
  },
  {
    slug: "bopp-plain-film",
    nameEn: "BOPP Plain Film",
    nameZh: "BOPP普通膜",
    category: "bopp-printing",
    descriptionEn: "Standard BOPP film for general packaging and printing applications.",
    descriptionZh: "标准BOPP薄膜，适用于一般包装和印刷应用。",
    thickness: "15-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Standard grade\nGood clarity\nEconomical\nPrintable",
    featuresZh: "标准级\n良好透明度\n经济实惠\n可印刷",
    applicationsEn: "General packaging\nPrinting\nLamination",
    applicationsZh: "一般包装\n印刷\n覆膜",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopp-plain.jpg",
    featured: true,
  },
  {
    slug: "bopet-ttr-film",
    nameEn: "BOPET TTR Film",
    nameZh: "BOPET热转印膜",
    category: "bopet-printing",
    descriptionEn: "BOPET film for thermal transfer ribbon production with excellent surface properties.",
    descriptionZh: "用于热转印碳带生产的BOPET薄膜，具有优异表面性能。",
    thickness: "4-6 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polyester",
    featuresEn: "Excellent surface properties\nHigh heat resistance\nGood dimensional stability\nSmooth surface",
    featuresZh: "优异表面性能\n高耐热性\n良好尺寸稳定性\n表面光滑",
    applicationsEn: "Thermal transfer ribbon\nPrinting\nLabeling",
    applicationsZh: "热转印碳带\n印刷\n标签",
    certifications: "ISO 9001",
    images: "/images/products/bopet-ttr.jpg",
    featured: true,
  },
  {
    slug: "bopet-metallized-film",
    nameEn: "BOPET Metallized Film",
    nameZh: "BOPET镀铝膜",
    category: "bopet-printing",
    descriptionEn: "Metallized BOPET film with excellent barrier properties for packaging applications.",
    descriptionZh: "镀铝BOPET薄膜，具有优异阻隔性能，适用于包装应用。",
    thickness: "12-350 microns",
    width: "200-5000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Silver",
    material: "Polyester",
    featuresEn: "Excellent barrier properties\nMetallic appearance\nHeat resistant\nPrintable",
    featuresZh: "优异阻隔性能\n金属外观\n耐热\n可印刷",
    applicationsEn: "Food packaging\nSnack packaging\nConfectionery",
    applicationsZh: "食品包装\n零食包装\n糖果",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopet-metallized.jpg",
    featured: true,
  },
  {
    slug: "bopet-plain-film",
    nameEn: "BOPET Plain Film",
    nameZh: "BOPET普通膜",
    category: "bopet-printing",
    descriptionEn: "Standard BOPET film with excellent optical and mechanical properties.",
    descriptionZh: "标准BOPET薄膜，具有优异光学和机械性能。",
    thickness: "12-350 microns",
    width: "200-5000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polyester",
    featuresEn: "High clarity\nGood tensile strength\nHeat resistant\nPrintable",
    featuresZh: "高透明度\n高拉伸强度\n耐热\n可印刷",
    applicationsEn: "Printing\nLamination\nPackaging",
    applicationsZh: "印刷\n覆膜\n包装",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopet-plain.jpg",
    featured: true,
  },
  {
    slug: "bopet-capacitor-film",
    nameEn: "BOPET Capacitor Film",
    nameZh: "BOPET电容器膜",
    category: "bopet-printing",
    descriptionEn: "Specialized BOPET film for capacitor applications with high purity and dielectric properties.",
    descriptionZh: "专用于电容器的BOPET薄膜，具有高纯度和介电性能。",
    thickness: "4-12 microns",
    width: "200-5000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polyester",
    featuresEn: "High purity\nExcellent dielectric properties\nLow dielectric loss\nHigh breakdown voltage",
    featuresZh: "高纯度\n优异介电性能\n低介电损耗\n高击穿电压",
    applicationsEn: "Capacitor manufacturing\nElectronics\nPower systems",
    applicationsZh: "电容器制造\n电子\n电力系统",
    certifications: "ISO 9001\nUL",
    images: "/images/products/bopet-capacitor.jpg",
    featured: true,
  },
  {
    slug: "pvdc-coating-film",
    nameEn: "PVDC Coating Film (K Film)",
    nameZh: "PVDC涂布膜（K膜）",
    category: "coating-film",
    descriptionEn: "PVDC coated film with excellent oxygen and moisture barrier properties for food packaging.",
    descriptionZh: "PVDC涂布膜，具有优异氧气和水蒸气阻隔性能，适用于食品包装。",
    thickness: "20-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "PVDC",
    featuresEn: "Excellent oxygen barrier\nGood moisture barrier\nHeat sealable\nPrintable",
    featuresZh: "优异氧气阻隔性\n良好水蒸气阻隔性\n可热封\n可印刷",
    applicationsEn: "Food packaging\nPharmaceutical packaging\nTobacco packaging",
    applicationsZh: "食品包装\n药品包装\n烟草包装",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/pvdc-coating.jpg",
    featured: true,
  },
  {
    slug: "bopp-packing-tape",
    nameEn: "BOPP Packing Tape",
    nameZh: "BOPP包装胶带",
    category: "packing-tape",
    descriptionEn: "High-quality BOPP adhesive tape for packaging and sealing applications.",
    descriptionZh: "高质量BOPP胶带，适用于包装和封箱应用。",
    thickness: "40-65 microns",
    width: "12-72mm",
    length: "100-1000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Strong adhesion\nHigh tensile strength\nWater resistant\nPrintable",
    featuresZh: "强粘性\n高拉伸强度\n防水\n可印刷",
    applicationsEn: "Box sealing\nPackaging\nShipping",
    applicationsZh: "封箱\n包装\n物流",
    certifications: "ISO 9001",
    images: "/images/products/bopp-tape.jpg",
    featured: true,
  },
  {
    slug: "cpp-film",
    nameEn: "CPP Film (Cast Polypropylene)",
    nameZh: "CPP流延膜",
    category: "bopp-printing",
    descriptionEn: "Cast polypropylene film with excellent heat sealability and transparency.",
    descriptionZh: "流延聚丙烯薄膜，具有优异热封性能和透明度。",
    thickness: "20-80 microns",
    width: "200-6000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polypropylene",
    featuresEn: "Excellent heat sealability\nHigh clarity\nGood flexibility\nPrintable",
    featuresZh: "优异热封性能\n高透明度\n柔韧性好\n可印刷",
    applicationsEn: "Food packaging\nSnack packaging\nConfectionery",
    applicationsZh: "食品包装\n零食包装\n糖果",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/cpp-film.jpg",
    featured: true,
  },
  {
    slug: "bopa-film",
    nameEn: "BOPA Film (Biaxially Oriented Nylon)",
    nameZh: "BOPA双向拉伸尼龙膜",
    category: "bopp-printing",
    descriptionEn: "Biaxially oriented nylon film with excellent puncture resistance and barrier properties.",
    descriptionZh: "双向拉伸尼龙薄膜，具有优异抗穿刺性能和阻隔性能。",
    thickness: "12-40 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Nylon",
    featuresEn: "Excellent puncture resistance\nGood barrier properties\nHeat resistant\nPrintable",
    featuresZh: "优异抗穿刺性能\n良好阻隔性\n耐热\n可印刷",
    applicationsEn: "Food packaging\nFrozen food packaging\nVacuum packaging",
    applicationsZh: "食品包装\n冷冻食品包装\n真空包装",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/bopa-film.jpg",
    featured: true,
  },
  {
    slug: "pof-shrink-film",
    nameEn: "POF Shrink Film",
    nameZh: "POF收缩膜",
    category: "bopp-printing",
    descriptionEn: "Polyolefin shrink film with excellent clarity and shrink properties.",
    descriptionZh: "聚烯烃收缩膜，具有优异透明度和收缩性能。",
    thickness: "12-25 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polyolefin",
    featuresEn: "Excellent clarity\nHigh shrink rate\nGood seal strength\nFDA approved",
    featuresZh: "优异透明度\n高收缩率\n良好封合强度\nFDA认证",
    applicationsEn: "Product wrapping\nFood packaging\nBeverage packaging",
    applicationsZh: "产品包装\n食品包装\n饮料包装",
    certifications: "ISO 9001\nFDA",
    images: "/images/products/pof-shrink.jpg",
    featured: true,
  },
  {
    slug: "bops-window-film",
    nameEn: "BOPS Window Film",
    nameZh: "BOPS窗口膜",
    category: "bopp-printing",
    descriptionEn: "Biaxially oriented polystyrene film for window envelope and display packaging.",
    descriptionZh: "双向拉伸聚苯乙烯薄膜，适用于窗口信封和展示包装。",
    thickness: "100-250 microns",
    width: "200-2000mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Transparent",
    material: "Polystyrene",
    featuresEn: "High clarity\nGood stiffness\nPrintable\nHeat sealable",
    featuresZh: "高透明度\n良好挺度\n可印刷\n可热封",
    applicationsEn: "Window envelopes\nDisplay packaging\nCard lamination",
    applicationsZh: "窗口信封\n展示包装\n卡片覆膜",
    certifications: "ISO 9001",
    images: "/images/products/bops-window.jpg",
    featured: true,
  },
  {
    slug: "tear-tape",
    nameEn: "Tear Tape",
    nameZh: "拉线",
    category: "tear-tape",
    descriptionEn: "Printed tear tape for cigarette and product packaging with easy-open functionality.",
    descriptionZh: "印刷拉线，用于香烟和产品包装，具有易开启功能。",
    thickness: "20-40 microns",
    width: "1.5-6mm",
    length: "3000-6000m",
    weight: "Customized",
    color: "Various",
    material: "Polypropylene",
    featuresEn: "Easy tear\nPrintable\nVarious widths\nFood grade",
    featuresZh: "易撕\n可印刷\n多种宽度\n食品级",
    applicationsEn: "Cigarette packaging\nProduct packaging\nSecurity sealing",
    applicationsZh: "香烟包装\n产品包装\n安全封条",
    certifications: "ISO 9001",
    images: "/images/products/tear-tape.jpg",
    featured: true,
  },
];

async function importProducts() {
  const API_URL = "https://blogweb-green.vercel.app/api/products/import";
  
  console.log(`准备导入 ${products.length} 个产品...`);
  
  try {
    const response = await fetch(API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-admin-password": "aecgroup2024",
      },
      body: JSON.stringify({ products }),
    });
    
    const result = await response.json();
    console.log("导入结果:", JSON.stringify(result, null, 2));
  } catch (error) {
    console.error("导入失败:", error);
  }
}

importProducts();